deployment:
  tasks:
    - export DEPLOYPATH=/home/utopiaetcom/awsugn.utopiaet.com
/awsugn.utopiaet.com/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH